### PR TITLE
localize address (fixes #29)

### LINKED ISSUE #29: address format localizations
the standard address format (french) is
10 Streetname

in german the address would be 
Streetname 10

how could this be implemented (besides overriding views)?

### PR DESCRIPTION
**Pull request by frisi**

### CODE REVIEW

**Comment by frisi** [comment]
as `street nr` seem to be more common (england, germany) i'd suggest to change the schema definition from

```python
ADDRESS_FIELDS = (
                'number',
                'street',
                'additional_address_details',
                'zip_code',
                'city',
                'region',
                'country',
                )
```

to

```
ADDRESS_FIELDS = (
                'street',
                'number',
                'additional_address_details',
                'zip_code',
                'city',
                'region',
                'country',
                )
```


would that change be ok for you in this pull request @vincentfretin

**Comment by vincentfretin** [comment]
Ok, so this is the order in the add or edit form. Yeah, I guess we can do this, but 
can you please create another constant for 
ADDRESS_FIELDS_PLUS_PARENT = ('use_parent_address', 'parent_address') + ADDRESS_FIELDS
so that French people can monkey patch the two constants to change the order again. Please add a changelog entry about that.

@tdesvenain @ebrehault Is this ok for you?

**Comment by vincentfretin** [comment]
For the monkey patching to work, we need the two constants to be a list so we can monkey patch the list in place.
```
from collective.contact.core import behaviors
behaviors.ADDRESS_FIELDS[0:2] = reversed(behaviors.ADDRESS_FIELDS[0:2])
behaviors.ADDRESS_FIELDS_PLUS_PARENT[2:4] = reversed(behaviors.ADDRESS_FIELDS[2:4])
```
Can you please check that this really work and document it in the README?

**Comment by frisi** [comment]
hi @vincentfretin 

i changed the default order and provided documentation for adding a patch that brings back the old behaviour in the readme.
as the `IContactDetails` interface uses `ADDRESS_FIELDS` (https://github.com/collective/collective.contact.core/blob/1.10/src/collective/contact/core/behaviors.py#L132) I don't see the point in adding another configuration for `ADDRESS_FIELDS_PLUS_PARENT`

**Comment by vincentfretin** [comment]
Does the patch really work? Do you really have the correct order? I thought the tuple for fields in the fieldset directive is evaluated before you monkey patch, no?

**Comment by frisi** [comment]
@vincentfretin i've tried that out and double checked it (on ordinary contacts) before committing to this PR.
i did not try it in combination with `use_parent_address` (i don't use organizations and postitions in my project)

**Comment by vincentfretin** [comment]
Ok, I'll test that before merging.

**Comment by frisi** [comment]
@vincentfretin great! a new release after merging this would be awesome.

**Comment by vincentfretin** [comment]
The patch with monkey:patch didn't work at all in the forms. I implemented my solution which work.

**Comment by vincentfretin** [comment]
1.11 released

**Comment by frisi** [comment]
i doubt you were using collective.monkeypatcher (correctly) if the patch did not work at all on your forms.

replies such as "did not work at all, implemented my solution which works"  don't encourage contributors.

anyway, i'm glad we have a way to change the order ofr street-and-number now ;-)

**Comment by frisi** [comment]
thanks for the release

**Comment by vincentfretin** [comment]
I'm sorry, maybe I did something wrong, I don't know. I tested in a pdb, the constant was indeed patched but it didn't change the order in the forms. My guess is that the import of behaviors is done first, so the tagged value for the fieldset directive is set on the interface, then the patch is done after that, so the ADDRESS_FIELDS in the tagged value was the old reference.
Maybe in your case it worked because the import of behaviors wasn't done before the patch somehow.

**Comment by vincentfretin** [comment]
It's actually in release 1.12. 1.11 was apparently already released the 2016-10-13 but the changelog wasn't up to date, @tdesvenain, you forgot to push the changes? You are using zest.releaser right?

**Comment by vincentfretin** [comment]
@tdesvenain @ebrehault For your project, you will need to override the address_line translation and add the patch when you upgrade to 1.12 to keep the current behavior, see the README. For Belgium, it's actually like for Germany. So it seems there is only in France where we want to number before the street.

Actually what we should really do is merge the two fields number and street, no?
And have really 3 fields correspond to the 3 potential lines of an address. For France, see
https://www.amabis.com/rediger-saisir-adresse-postale/
The current field additional address detail is ambiguous, in this the first or third line of the adress?
I'm not planning to work on it for now, but if someone want to work on it, please do.

**Pull request merged**
