### PR TITLE
Plone5

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by agitator** [comment]
Should this already be a 2.0 release?
Next steps would be degroking and py3 also @tdesvenain work on https://github.com/collective/collective.contact.core/blob/plone5-mockup/CHANGES.rst which is marked as 2.0? 
Also go for https://semver.org in future releases?

**Comment by sgeulette** [comment]
Our original idea was to keep a master version compatible with plone4 and 5.
We have indeed hundreds instances under Plone 4.
If it's not easily possible, could you create a 1.x branch for plone 4 ? On modified related products too.
I'm personally not yet using Plone 5 but I will review as far as possible.
Regards

**Comment by agitator** [comment]
Right now Plone 4/5 compatibility should be given on this branch and keep it a 1.x?
So maybe branch of master to a 1.x before merging plone5-mockup and py3 changes?
From that point on it doesn't make much sense for me to try to keep compatibility and will have a much cleaner and saner stack to move on?

**Comment by sgeulette** [comment]
I see that some functionalities have been disabled in the plone5 branch. 
It's better to branch actual master to 1.x before merging actual plone5 branch and continue migration work in master.

**Comment by agitator** [comment]
I started working on a Plone5 only version in https://github.com/collective/collective.contact.core/pull/66 

As discussed, I'll make a 1.x branch for Plone 4 from master before merging and master will be a 2.x version.

**Pull request closed without merging**
