### PR TITLE
add person email to searchabletext

### PR DESCRIPTION
**Pull request by frisi**
if you get smtp errors when sending a newsletter with collectice.contact.mailaction there is no way to search for a contact by email currently.

### CODE REVIEW

**Comment by tdesvenain** [comment]
thanks for your proposal
why person only ?
this could be accurate for any content that implements IContactDetails interface / behavior

**Comment by frisi** [comment]
@tdesvenain thanks, i was anticipating a reply like this but first wanted to know if you like the idea at all.
i added a second commit adding the email for all types having the `IContactDetails` behavior.

i guess it does not make much sense for positions, but they do have the behavior too.

**Comment by frisi** [comment]
@sgeulette there is no specific setting yet.

do you require this to be configurable to be merged?

if yes there are two possiblities:

* re-use `collective.contact.core.interfaces.IContactCoreParameters.use_description_to_search_person`
* or add (yet) another setting for the email. which i did not do for simplicity here.

**Comment by sgeulette** [comment]
@frisi 
Not a requirement. 
Questioning if it could slowdown queries on big database (300000 items) with 10000 contacts.

**Comment by frisi** [comment]
> Questioning if it could slowdown queries on big database (300000 items) with 10000 contacts.

i don't think so: we don't add additional queries or make existing ones more complex. searchabletext is built to handle richtext fields so adding another word (email address in this case) should not hurt at all performance-wise.

**Comment by frisi** [comment]
thanks for your feedback @sgeulette  and @tdesvenain 
could you please merge and make a new release or add me to pypi (user frisi) so i can do it using zest.releaser

**Comment by sgeulette** [comment]
@frisi you can now release on pypi

**Comment by frisi** [comment]
thanks release is done.
have a nice day!

**Pull request merged**
